### ISSUE TITLE
remove several domains from multi_source_domains

### ISSUE THREAD

**Issue by cyh03223** [Guliisgreat/VDPG#2]
Hi I see some codes like: # multi_source_domains.remove('quickdraw')
        # multi_source_domains.remove('painting')
        # multi_source_domains.remove('sketch')
        # multi_source_domains.remove('real'),
But while I try to uncomment and run them I get:
Traceback (most recent call last):
  File "/root/autodl-tmp/VDPG/train.py", line 140, in main
    metric_dict, _ = train(cfg)
  File "/root/autodl-tmp/VDPG/src/utils/utils.py", line 75, in wrap
    raise ex
  File "/root/autodl-tmp/VDPG/src/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/root/autodl-tmp/VDPG/train.py", line 112, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 538, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 68, in _call_and_handle_interrupt
    trainer._teardown()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1008, in _teardown
    loop.teardown()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 411, in teardown
    self._data_fetcher.teardown()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 79, in teardown
    self.reset()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 141, in reset
    super().reset()
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/loops/fetchers.py", line 75, in reset
    self.length = sized_len(self.combined_loader)
  File "/root/miniconda3/lib/python3.10/site-packages/lightning_fabric/utilities/data.py", line 51, in sized_len
    length = len(dataloader)  # type: ignore [arg-type]
  File "/root/miniconda3/lib/python3.10/site-packages/pytorch_lightning/utilities/combined_loader.py", line 358, in __len__
    raise RuntimeError("Please call `iter(combined_loader)` first.")
RuntimeError: Please call `iter(combined_loader)` first.

Please tell me if you experience this

**Comment by cyh03223** [comment]
src/datasets/dataloader.py line 254, change into replace=True
